@ECommerceApp_HostAddress = http://localhost:5179

GET {{ECommerceApp_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{ECommerceApp_HostAddress}}/api/Product/
Accept: application/json

###
